### ISSUE TITLE
다음 미팅까지 할 일

### ISSUE THREAD

**Issue by jaeyo03** [Capstone-Design-FitFit/Frontend_Nextjs#13]
## ✅ Description
다음 미팅까지 할 일

## ✔️ TODO
- [ ] 업로드한 포즈 삭제하고, 업로드한 옷 사진 삭제
- [ ] 그리드 그리는거 완성
- [x] 와이어프레임 제대로 완성
