### ISSUE TITLE
수요일까지 TODO

### ISSUE THREAD

**Issue by jaeyo03** [Capstone-Design-FitFit/Frontend_Nextjs#16]
## ✅ Description
설명을 작성하세요.
## ✔️ TODO
- [ ] image를 camera capture에 전송
- [ ] 그리드 그리기 보완
- [ ] 사진 삭제 기능
- [ ] 사진 고르는 기능
